clc, clear, close all;

%% Environment setup
this_file = mfilename('fullpath');
exp_dir = fileparts(this_file);
repo_root = fileparts(exp_dir);
addpath(fullfile(repo_root, 'utils'));
addpath(fullfile(repo_root, 'Functions'));
addpath(fullfile(repo_root, 'tools'));

%% Load optimized parameters and data
% Note: Using the .mat file generated by data_process.m
load(fullfile(exp_dir, 'mat_data', 'optimized_params.mat'), 'params', 'test_points', 'b_total');

% Re-load scan_records to get R_true (since optimized_params.mat might only have p_true/theta_true)
load(fullfile(exp_dir, 'mat_data', 'scan_records.mat'), 'scan_records');

% Extract parameters
m_pos = params.magnet.m_pos;
m_hat = params.magnet.m_hat;
m_norm = params.magnet.m_norm;
d_list_full = params.sensor.d_list;

% Pre-calculate sensor array max norm (radius)
max_d_full = max(vecnorm(d_list_full));

N = size(b_total, 3);
err_fro = zeros(N, 1);
err_ratio = zeros(N, 1);
ratio_full = zeros(N, 1);

fprintf('Processing %d test points: Comparing Tensor Estimation and n1/n2 Ratio...\n', N);

for i = 1:N
    p_true = test_points(i).p_true;
    
    % R_true: orientation of sensor array in global frame
    R_true = quat2rotm([scan_records(i).poses.diana7.orientation(4), ...
                        scan_records(i).poses.diana7.orientation(1), ...
                        scan_records(i).poses.diana7.orientation(2), ...
                        scan_records(i).poses.diana7.orientation(3)]);

    % 1. Calculate Analytical Field and Gradient (Global)
    [b_p_global, A_p_global] = calcFieldAndGradient(p_true, m_pos, m_hat, m_norm);

    for j = 1:size(d_list_full, 2)
        [b_p_global_model(:, j), ~] = calcFieldAndGradient(p_true + R_true * d_list_full(:, j), m_pos, m_hat, m_norm);
    end
    
    % 2. First-order Taylor Term (n2): ||nabla * Rd||
    first_order_terms = A_p_global' * R_true * d_list_full; 
    n2 = norm(first_order_terms, 'fro');

    % 3. Higher-order residual (n1): ||b_meas - b_center - nabla * Rd||
    b_local_meas = b_total(:, :, i);

    higher_order_terms = b_p_global_model - b_p_global - first_order_terms;
    n1 = norm(higher_order_terms, 'fro');
    
    % 4. Error Ratio: n1 / n2 (Model Linearization Mismatch)
    err_ratio(i) = n1 / n2;
    
    % 5. Estimate Local Gradient Tensor from Measurements
    [X_local_est, ~, ~, ~] = lc_grad_tensor_estimator(b_local_meas, d_list_full);
    X_global_est = R_true * X_local_est * R_true';
    
    % 6. Tensor Estimation Error (Frobenius Norm)
    err_fro(i) = norm(A_p_global - X_global_est, 'fro') / norm(A_p_global, 'fro');
    
    % 7. Calculate Aperture Ratio (l/r)
    dist_to_source = norm(p_true - mean(m_pos, 2));
    ratio_full(i) = max_d_full / dist_to_source;
end

%% Visualization
% Standard figure settings for 19.8cm width (Double Column)
%% Visualization
fig_dim = 12; 
set(groot, 'DefaultTextInterpreter', 'latex');
set(groot, 'DefaultAxesTickLabelInterpreter', 'latex');
set(groot, 'DefaultLegendInterpreter', 'latex');

figure('Name', 'Field Linearization Accuracy Analysis', 'Color', 'w');
set(gcf, 'Units', 'centimeters');
set(gcf, 'Position', [5, 5, fig_dim, fig_dim]);

hold on; grid on; box on;
scatter(ratio_full, err_ratio, 30, 'filled', 'MarkerFaceAlpha', 0.5, 'MarkerFaceColor', [0.85 0.33 0.1]);
p_ratio = polyfit(ratio_full, err_ratio, 1);
plot(ratio_full, polyval(p_ratio, ratio_full), 'k-', 'LineWidth', 1.5);

legend({'Measured Residual', 'Linear Fit'}, 'FontSize', 14, 'Location', 'northwest', 'Box', 'off');

axis square;

xlabel('$\ell/r$', 'FontSize', 16);
ylabel('$ $', 'FontSize', 16);
set(gca, 'FontSize', 16);

% Export the figure
export_fig 'field_linearization_analysis.png' -r300;

fprintf('Analysis complete and figure exported.\n');

